# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.10

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_dev.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script: nox

# deploy new versions to PyPI
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user:
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: 
#    python: 3.10